# Generated by Django 5.2.1 on 2025-08-25 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attempt',
            name='current_difficulty',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='attempt',
            name='current_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.attempt'),
        ),
    ]
