# Generated by Django 5.2.1 on 2025-09-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_sets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Duration of the set in minutes'),
        ),
    ]
